NeptuneClusterSubnet:
  Type: "AWS::Neptune::DBSubnetGroup"
  Properties:
    DBSubnetGroupDescription: Subnets for the {{cluster.name}} cluster
    DBSubnetGroupName: {{cluster.name}}
    SubnetIds:
      "Fn::Split": [",", {"Ref": Subnets}]
    Tags:
      {{#each tags}}
      - Key: {{Key}}
        Value: {{Value}}
      {{/each}}

NeptuneCluster:
  DependsOn:
    - NeptuneClusterSubnet
  Type: "AWS::Neptune::DBCluster"
  Properties:
    DBClusterIdentifier: {{cluster.name}}
    AvailabilityZones:
      "Fn::Split": [",", {"Ref": AvailabilityZones}]
    VpcSecurityGroupIds:
      "Fn::Split": [",", {"Ref": SecurityGroups}]
    DBSubnetGroupName: {{cluster.name}}
    PreferredBackupWindow: {{cluster.backupWindow}}
    PreferredMaintenanceWindow: {{cluster.maintenanceWindow}}
    {{#if cluster.backupTTL}}
    BackupRetentionPeriod: {{cluster.backupTTL}}
    {{/if}}
    Port: 8182
    IamAuthEnabled: false
    StorageEncrypted: true
    Tags:
      {{#each tags}}
      - Key: {{Key}}
        Value: {{Value}}
      {{/each}}

NeptuneInstance:
  DependsOn:
    - NeptuneCluster
    - NeptuneClusterSubnet
  Type: "AWS::Neptune::DBInstance"
  Properties:
    AllowMajorVersionUpgrade: false
    AutoMinorVersionUpgrade: true
    AvailabilityZone:
      "Fn::Select": [0, "Fn::Split": [",", {"Ref": AvailabilityZones}]]
    DBClusterIdentifier: {{cluster.name}}
    DBInstanceClass: {{cluster.type}}
    DBInstanceIdentifier: {{cluster.name}}-main
    DBSubnetGroupName: {{cluster.name}}
    PreferredMaintenanceWindow: {{cluster.maintenanceWindow}}
    Tags:
      {{#each tags}}
      - Key: {{Key}}
        Value: {{Value}}
      {{/each}}

NeptuneInstanceReplica:
  DependsOn:
    - NeptuneCluster
    - NeptuneClusterSubnet
    - NeptuneInstance
  Type: "AWS::Neptune::DBInstance"
  Properties:
    AllowMajorVersionUpgrade: false
    AutoMinorVersionUpgrade: true
    AvailabilityZone:
      "Fn::Select": [1, "Fn::Split": [",", {"Ref": AvailabilityZones}]]
    DBClusterIdentifier: {{cluster.name}}
    DBInstanceClass: {{cluster.type}}
    DBInstanceIdentifier: {{cluster.name}}-replica
    DBSubnetGroupName: {{cluster.name}}
    PreferredMaintenanceWindow: {{cluster.replicaMaintenanceWindow}}
    Tags:
      {{#each tags}}
      - Key: {{Key}}
        Value: {{Value}}
      {{/each}}
